/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab.pkg01;

import java.text.DecimalFormat;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.File;
        
/**
 *
 * @author Krunkalicious
 */
public class Lab01 extends javax.swing.JFrame {

    /**
     * Creates new form Lab01
     */
    public Lab01() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tbGross = new javax.swing.JTextField();
        lblMedicare = new javax.swing.JLabel();
        lblSocial = new javax.swing.JLabel();
        lblNet = new javax.swing.JLabel();
        btnCalc = new javax.swing.JButton();
        rdoMarried = new javax.swing.JRadioButton();
        rdoSingle = new javax.swing.JRadioButton();
        cbPayPeriod = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblFederal = new javax.swing.JLabel();
        tbDependents = new javax.swing.JTextField();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuSave = new javax.swing.JMenuItem();
        menuClear = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenuItem();
        menuPrint = new javax.swing.JMenu();
        menuReport = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Federal Tax");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Social Security");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Gross");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Medicare");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Net");

        lblMedicare.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMedicare.setAlignmentX(0.5F);
        lblMedicare.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblSocial.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSocial.setAlignmentX(0.5F);
        lblSocial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblNet.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNet.setAlignmentX(0.5F);
        lblNet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnCalc.setText("Calculate");
        btnCalc.setPreferredSize(new java.awt.Dimension(90, 25));
        btnCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoMarried);
        rdoMarried.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdoMarried.setText("Married");
        rdoMarried.setPreferredSize(new java.awt.Dimension(90, 25));
        rdoMarried.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoMarriedActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoSingle);
        rdoSingle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdoSingle.setSelected(true);
        rdoSingle.setText("Single");
        rdoSingle.setPreferredSize(new java.awt.Dimension(90, 25));
        rdoSingle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoSingleActionPerformed(evt);
            }
        });

        cbPayPeriod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Weekly", "Bi-Weekly", "Semi-Monthly", "Monthly" }));
        cbPayPeriod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPayPeriodActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Dependents");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("PayPeriod");

        lblFederal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFederal.setAlignmentX(0.5F);
        lblFederal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tbDependents.setText("0");
        tbDependents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbDependentsActionPerformed(evt);
            }
        });

        menuFile.setText("File");

        menuSave.setText("Save");
        menuSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSaveActionPerformed(evt);
            }
        });
        menuFile.add(menuSave);

        menuClear.setText("Clear");
        menuClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClearActionPerformed(evt);
            }
        });
        menuFile.add(menuClear);

        menuExit.setText("Exit");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        menuFile.add(menuExit);

        menuBar.add(menuFile);

        menuPrint.setText("Print");

        menuReport.setText("Print Report");
        menuReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportActionPerformed(evt);
            }
        });
        menuPrint.add(menuReport);

        menuBar.add(menuPrint);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(101, 101, 101)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbPayPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tbDependents, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(97, 97, 97)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblMedicare, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblNet, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(lblFederal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tbGross, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(btnCalc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rdoSingle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(rdoMarried, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdoMarried, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdoSingle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tbDependents, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbPayPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbGross, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFederal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblMedicare, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblNet, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(btnCalc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        double gross = 0;
        double taxableGross = 0;
        int dependents = 0;
        double withholding = 0;
        double fedTax = 0;
        double socialSec = 0;
        double mediCare = 0;
        double net = 0;
    
    
    private void btnCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcActionPerformed

        
        gross = Double.parseDouble(tbGross.getText());
        dependents = Integer.parseInt(tbDependents.getText());
        
        switch (cbPayPeriod.getSelectedIndex()) {
            case 0:
                withholding = dependents * 77.90;
                break;
            case 1:
                withholding = dependents * 155.80;
                break;
            case 2:
                withholding = dependents * 168.80;
                break;
            case 3:
                withholding = dependents *337.50;
                break;
            default:
                break;
        }
        
        taxableGross = gross - withholding;
        
        if (rdoSingle.isSelected())
        {
            {
            if (taxableGross < 88)
                {
                fedTax = 0;
                socialSec = gross * .062;
                mediCare = gross * .0145;
                net = gross - fedTax - socialSec - mediCare;
                }
            
            else if (taxableGross > 88 && taxableGross < 447)
                {
                fedTax = ((taxableGross - 88) *.10) + 0;
                socialSec = gross * .062;
                mediCare = gross * .0145;
                net = gross - fedTax - socialSec - mediCare; 
                }
            
            else if (taxableGross > 447 && taxableGross < 1548)
                {
                fedTax = ((taxableGross - 447) *.15) + 35.90;
                socialSec = gross * .062;
                mediCare = gross * .0145;
                net = gross - fedTax - socialSec - mediCare; 
                }
            
            else if (taxableGross > 1548 && taxableGross < 3623)
                {
                fedTax = ((taxableGross - 1548) *.25) + 201.05;
                socialSec = gross * .062;
                mediCare = gross * .0145;
                net = gross - fedTax - socialSec - mediCare; 
                }
            
            else if (taxableGross > 3623 && taxableGross < 7460)
                {
                fedTax = ((taxableGross - 333) *.28) + 719.80;
                socialSec = gross * .062;
                mediCare = gross * .0145;
                net = gross - fedTax - socialSec - mediCare; 
                }
            
            else if (taxableGross > 7460 && taxableGross < 16115)
                {
                fedTax = ((taxableGross - 7460) *.33) + 1794.16;
                socialSec = gross * .062;
                mediCare = gross * .0145;
                net = gross - fedTax - socialSec - mediCare; 
                }
            
            else if (taxableGross > 16115 && taxableGross < 16181)
                {
                fedTax = ((taxableGross - 16115) *.35) + 4650.31;
                socialSec = gross * .062;
                mediCare = gross * .0145;
                net = gross - fedTax - socialSec - mediCare; 
                }
            
            else if (taxableGross > 16181)
                {
                fedTax = ((taxableGross - 16181) *.396) + 4673.41;
                socialSec = gross * .062;
                mediCare = gross * .0145;
                net = gross - fedTax - socialSec - mediCare; 
                }
 
            }
         
        }
        
        else
        {
            {
            if (taxableGross < 333)
                {
                fedTax = 0;
                socialSec = gross * .062;
                mediCare = gross * .0145;
                net = gross - fedTax - socialSec - mediCare;
                }
            
            else if (taxableGross > 333 && taxableGross < 1050)
                {
                fedTax = ((taxableGross - 333) *.10) + 0;
                socialSec = gross * .062;
                mediCare = gross * .0145;
                net = gross - fedTax - socialSec - mediCare; 
                }
            
            else if (taxableGross > 1050 && taxableGross < 3252)
                {
                fedTax = ((taxableGross - 1050) *.15) + 71.70;
                socialSec = gross * .062;
                mediCare = gross * .0145;
                net = gross - fedTax - socialSec - mediCare;
                }
            
            else if (taxableGross > 3252 && taxableGross < 6221)
                {
                fedTax = ((taxableGross - 3252) *.25) + 402;
                socialSec = gross * .062;
                mediCare = gross * .0145;
                net = gross - fedTax - socialSec - mediCare;
                } 
            
            else if (taxableGross > 6221 && taxableGross < 9308)
                {
                fedTax = ((taxableGross - 6221) *.28) + 1144.25;
                socialSec = gross * .062;
                mediCare = gross * .0145;
                net = gross - fedTax - socialSec - mediCare;
                }
            
            else if (taxableGross > 9308 && taxableGross < 16360)
                {
                fedTax = ((taxableGross - 9308) *.33) + 2008.61;
                socialSec = gross * .062;
                mediCare = gross * .0145;
                net = gross - fedTax - socialSec - mediCare;
                }
            
            else if (taxableGross > 16360 && taxableGross < 18437)
                {
                fedTax = ((taxableGross - 16360) *.35) + 4335.77;
                socialSec = gross * .062;
                mediCare = gross * .0145;
                net = gross - fedTax - socialSec - mediCare;
                }
            
            else if (taxableGross < 18437)
                {
                fedTax = ((taxableGross - 18437) *.396) + 5062.72;
                socialSec = gross * .062;
                mediCare = gross * .0145;
                net = gross - fedTax - socialSec - mediCare;
                }
            
            }
        }    
        
        DecimalFormat df = new DecimalFormat("0.00");
        
        lblFederal.setText(df.format(fedTax));
        lblSocial.setText(df.format(socialSec));
        lblMedicare.setText(df.format(mediCare));
        lblNet.setText(df.format(net));
        
    }//GEN-LAST:event_btnCalcActionPerformed

    private void rdoSingleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoSingleActionPerformed
        tbGross.setText("");
        tbDependents.setText("");
        lblSocial.setText("");
        lblMedicare.setText("");
        lblNet.setText("");
        lblFederal.setText("");
    }//GEN-LAST:event_rdoSingleActionPerformed

    private void rdoMarriedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoMarriedActionPerformed
        tbGross.setText("");
        tbDependents.setText("");
        lblSocial.setText("");
        lblMedicare.setText("");
        lblNet.setText("");
        lblFederal.setText("");
    }//GEN-LAST:event_rdoMarriedActionPerformed

    private void cbPayPeriodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPayPeriodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPayPeriodActionPerformed

    private void tbDependentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbDependentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbDependentsActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        System.exit (0);
    }//GEN-LAST:event_menuExitActionPerformed

    private void menuReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportActionPerformed
        String report = "Federal:     $" + "  " + lblFederal.getText();
        report = report + "\n" + "Social:        $" + "  " + lblSocial.getText() + 
                          "\n" + "Medicare:   $" + "  " + lblMedicare.getText() + 
                          "\n" + "Net  :           $" + "  " + lblNet.getText();
        Report newframe = new Report(report);
        newframe.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_menuReportActionPerformed

    private void menuSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSaveActionPerformed
        try {
            FileWriter writer = new FileWriter("MyFile.txt");
            if (rdoSingle.isSelected())
            {
                writer.write("Single");
                writer.write("\r\n");
            }
            else
            {
                writer.write("Married");
                writer.write("\r\n");
            }
            writer.write(tbDependents.getText());
            writer.write("\r\n");
            
            switch (cbPayPeriod.getSelectedIndex()) {
                case 0:
                    writer.write("Weekly");
                    break;
                case 1:
                    writer.write("Bi-Weekly");
                    break;
                case 2:
                    writer.write("Semi-Monthly");
                    break;
                case 3:
                    writer.write("Monthly");
                    break;
                default:
                    break;
            }
            writer.write("\r\n");
            writer.write(tbGross.getText());
            writer.write("\r\n");
            writer.write(lblFederal.getText());
            writer.write("\r\n");
            writer.write(lblSocial.getText());
            writer.write("\r\n");
            writer.write(lblMedicare.getText());
            writer.write("\r\n");
            writer.write(lblNet.getText());
            writer.write("\r\n");
            writer.write("EOF");
            writer.close();
        } catch (IOException e) {
            
        }
    }//GEN-LAST:event_menuSaveActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            String[] value;
            try (FileReader reader = new FileReader("MyFile.txt")) {
                BufferedReader bufferedreader = new BufferedReader(reader);
                value = new String[9];
                String line;
                int x = 0;
                while ((line = bufferedreader.readLine()) !=null)
                {
                    value[x] = line;
                    x++;
                }
            }
            
            if (!"Single".equals(value[0]))
            {
                rdoMarried.setSelected(true);
            }
            else
            {
                rdoSingle.setSelected(true);
            }
            
            tbDependents.setText(value[1]);
            
            if (null != value[2])
            switch (value[2]) {
                case "Weekly":
                    cbPayPeriod.setSelectedIndex(0);
                    break;
                case "Bi-Weekly":
                    cbPayPeriod.setSelectedIndex(1);
                    break;
                case "Semi-Monthly":
                    cbPayPeriod.setSelectedIndex(2);
                    break;
                case "Monthly":
                    cbPayPeriod.setSelectedIndex(3);
                    break;
                default:
                    break;
            }
            
            tbGross.setText(value[3]);
            lblFederal.setText(value[4]);
            lblSocial.setText(value[5]);
            lblMedicare.setText(value[6]);
            lblNet.setText(value[7]);
            
            
        } catch (IOException e) {
            
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void menuClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClearActionPerformed
        File myFile = new File("MyFile.txt");
        myFile.delete();
    }//GEN-LAST:event_menuClearActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalc;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbPayPeriod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblFederal;
    private javax.swing.JLabel lblMedicare;
    private javax.swing.JLabel lblNet;
    private javax.swing.JLabel lblSocial;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuClear;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuPrint;
    private javax.swing.JMenuItem menuReport;
    private javax.swing.JMenuItem menuSave;
    private javax.swing.JRadioButton rdoMarried;
    private javax.swing.JRadioButton rdoSingle;
    private javax.swing.JTextField tbDependents;
    private javax.swing.JTextField tbGross;
    // End of variables declaration//GEN-END:variables
}
